version: '3'

networks:
  skynet:
    name: zen-skynet
    driver: bridge

volumes:
  zen-mongodata:
    name: 'zen-mongodata'

services:
  rahbit:
    image: rabbitmq:3
    container_name: rahbit
    ports: [ 5672:5672, 15672:15672 ]
    environment:
      RABBITMQ_DEFAULT_USER: 'rah'
      RABBITMQ_DEFAULT_PASS: 'bit'
  monguito:
    image: mongo:6
    container_name: monguito
    command: 'mongod --replSet rs0 --bind_ip_all'
    ports: [ 27017:27017 ]
    volumes: [ 'zen-mongodata:/data/db' ]
    networks: [ skynet ]
  monguito_init:
    # this contianer will exit once the replica set is initiated
    image: mongo:6
    container_name: monguito_init
    restart: 'no'
    depends_on: [ monguito ]
    networks: [ skynet ]
    command: >-
      mongosh --host host.docker.internal:27017 --eval 'rs.initiate({
        "_id": "rs0",
        "members": [
          {
            "_id":0,
            "host": "host.docker.internal:27017"
          }
        ]
      });'
  banks-api:
    build:
      context: .
    image: zen/banks-api
    container_name: zen-banks-api
    env_file: [ .env ]
    ports:
      - 30000:3000
      - 30001:9229
    command: 'sh -c "npm i && npm run start:debug"'
    volumes: [ '.:/app', '/app/node_modules' ]
    networks: [ skynet ]
    depends_on: [ monguito ]
